### ISSUE TITLE
Investigate on SMTP problems: why the hell is it not sending to outbound accounts from my code?

### ISSUE THREAD

**Issue by afederici75** [FirePonyCreativeSociety/MatchBox#16]

**Comment by rechner** [comment]
In our particular configuration, this came down to needing to use port 465 (SSL) instead of 587 (STARTTLS)

**Comment by afederici75** [comment]
@rechner  This is how I have it setup on Azure. Port 465 does not work there. Are you saying it works in the VDF container you stood up? (Just trying to understand your comment)
![image](https://user-images.githubusercontent.com/13766049/82615908-a3491a00-9b99-11ea-90b7-fa7359fe15fc.png)
