### ISSUE TITLE
Find a way to store DB files outside the container or something

### ISSUE THREAD

**Issue by afederici75** [FirePonyCreativeSociety/MatchBox#17]

**Comment by rechner** [comment]
The prescribed way to do this in Docker is to use a volume bind with the `-v /path/outside/container:/path/inside/container`.

For production, I'd recommend bundling and hooking up sqlserver in a docker-compose.

**Comment by afederici75** [comment]
@rechner sounds good overall, so you want meto try setting up a SQL server instance on Azure to make sure it works (then maybe I give you step-by-step instructions, if needed)? Which also implies we're moving away from the embedded Sqllite in favor of a more reliable data storage solution, right?
